routes/web.php
<?php

use App\Models\User;
use App\Notifications\ContactFormNotification;
use App\Notifications\OpenTicketNotify;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('homepage');
})->name('home');

Route::view('/individuals', 'individuals')->name('individuals');
Route::view('/investors', 'investors')->name('investors');
Route::view('/law_firms', 'law-firms')->name('law-firms');
Route::view('/businesses', 'businesses')->name('businesses');
Route::view('/blacklist', 'blacklist')->name('blacklist');
Route::post('/contact-form', function (Request $request){
    $user = User::where('isAdmin',1)->first();

    $user->notify(new ContactFormNotification($request->name, $request->email, $request->message));
    return redirect()->route('home');
})->name('contact-form');

Route::get('/artisan', function (){
    $clear_cache = Artisan::call('route:clear');
    $clear_cache = Artisan::call('config:clear');
    $clear_cache = Artisan::call('view:clear');
    $clear_cache = Artisan::call('optimize');

    echo "done all";
});

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//user routes


Route::group([
    'as' => 'user.',
    'middleware' => ['isUser','auth']
], function (){
    Route::get('dashboard', [\App\Http\Controllers\UserController::class,'index'])->name('dashboard');
    Route::get('self-service', [\App\Http\Controllers\UserController::class,'self_service'])->name('self-service');
    Route::post('self-service-post', [\App\Http\Controllers\UserController::class,'self_service_post'])->name('self-service-post');
    Route::get('open-case', [\App\Http\Controllers\UserController::class,'open_case'])->name('open-case');
    Route::post('open-case-post', [\App\Http\Controllers\UserController::class,'open_case_post'])->name('open-case-post');
    Route::get('all-cases', [\App\Http\Controllers\UserController::class,'all_cases'])->name('all-cases');
    Route::get('all-cases/{id}', [\App\Http\Controllers\UserController::class,'all_cases_page'])->name('all-cases-page');
    Route::get('all-users', [\App\Http\Controllers\UserController::class,'all_users'])->name('all-users');
});

//admin routes
Route::group([
    'as' => 'admin.',
    'middleware' => ['isAdmin','auth'],
    'prefix' => 'admin'
], function (){
    Route::get('/dashboard', [\App\Http\Controllers\AdminController::class,'dashboard'])->name('dashboard');
    Route::get('all-users', [\App\Http\Controllers\AdminController::class,'all_users'])->name('all-users');
    Route::get('all-cases', [\App\Http\Controllers\AdminController::class,'all_cases'])->name('all-cases');
    Route::delete('/delete-user/{id}', [\App\Http\Controllers\AdminController::class,'delete_user'])->name('delete-user');
    Route::patch('/reopen-casereopen-case/{id}', [\App\Http\Controllers\AdminController::class,'reopen_case'])->name('reopen-case');
    Route::delete('/delete-case-case/{id}', [\App\Http\Controllers\AdminController::class,'delete_case'])->name('delete-case');
    Route::get('all-cases/{id}', [\App\Http\Controllers\AdminController::class,'all_cases_page'])->name('all-cases-page');
    Route::get('/take-case/{id}', [\App\Http\Controllers\AdminController::class, 'take_case'])->name('take-case');
    Route::get('/close-case/{id}', [\App\Http\Controllers\AdminController::class, 'close_case'])->name('close-case');

});

resources/views/layouts/admindash.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdminLTE 3 | Dashboard</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{ asset('plugins/fontawesome-free/css/all.min.css') }}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="{{ asset('plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{{ asset('plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{{ asset('plugins/jqvmap/jqvmap.min.css') }}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('dist/css/adminlte.min.css') }}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{{ asset('plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{{ asset('plugins/daterangepicker/daterangepicker.css') }}">
    <!-- summernote -->
    <link rel="stylesheet" href="{{ asset('plugins/summernote/summernote-bs4.min.css') }}">

</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Preloader -->
    <div class="preloader flex-column justify-content-center align-items-center">
        <img class="animation__shake" src="{{ asset('dist/img/AdminLTELogo.png') }}" alt="AdminLTELogo" height="60" width="60">
    </div>

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>

        </ul>

        <!-- Right navbar links -->

    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{{ route('home') }}" class="brand-link">
            <img src="{{ asset('dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">Admin Portal</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                {{--                <div class="image">--}}
                {{--                    <img src="dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">--}}
                {{--                </div>--}}
                <div class="info">
                    <a href="#" class="d-block">Admin User</a>
                </div>
            </div>

            <!-- SidebarSearch Form -->
            <div class="form-inline">
                <div class="input-group" data-widget="sidebar-search">
                    <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-sidebar">
                            <i class="fas fa-search fa-fw"></i>
                        </button>
                    </div>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->

                    <li class="nav-item">
                        <a href="{{ route('admin.dashboard') }}" class="nav-link">
                            <i class="nav-icon fas fa-th"></i>
                            <p>
                                Dashboard

                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{{ route('admin.all-users') }}" class="nav-link">
                            <i class="nav-icon fas fa-table"></i>
                            <p>
                                All Users

                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="{{ route('admin.all-cases') }}" class="nav-link">
                            <i class="nav-icon fas fa-file"></i>
                            <p>
                                All Cases

                            </p>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit() " class="nav-link">
                            <i class="nav-icon far fa-circle text-danger"></i>
                            <p>Logout</p>
                        </a>

                        <form action="{{ route('logout') }}" id="logout-form" method="post">
                            @csrf
                        </form>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>
@yield('content')

    <footer class="main-footer">

        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 3.2.0
        </div>
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('plugins/chart.js/Chart.min.js') }}"></script>
<!-- Sparkline -->
<script src="{{ asset('plugins/sparklines/sparkline.js') }}"></script>
<!-- JQVMap -->
<script src="{{ asset('plugins/jqvmap/jquery.vmap.min.js') }}"></script>
<script src="{{ asset('plugins/jqvmap/maps/jquery.vmap.usa.js') }}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('plugins/jquery-knob/jquery.knob.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('dist/js/demo.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('dist/js/pages/dashboard.js') }}"></script>

<script src="https://cdn.datatables.net/2.0.2/css/dataTables.dataTables.min.css"></script>
<script src="https://cdn.datatables.net/2.0.2/js/dataTables.min.js"></script>

@stack('custom-script')
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/userdash.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Template Mo">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">

    <title>Dashboard - Allrefund</title>
    <!--

    ART FACTORY

    https://templatemo.com/tm-537-art-factory

    -->
    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/font-awesome.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/templatemo-art-factory.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/owl-carousel.css') }}">
    <style>
        .icon{
            -webkit-transition: all 0.3s ease 0s;
            -moz-transition: all 0.3s ease 0s;
            -o-transition: all 0.3s ease 0s;
            transition: all 0.3s ease 0s;
            width: 90px;
            height: 90px;
            line-height: 90px;
            margin: auto;
            margin-bottom: auto;
            position: relative;
            margin-bottom: 30px;
            background: #8261ee;
            -webkit-border-radius: 50%;
            -moz-border-radius: 50%;
            border-radius: 50%;
        }
    </style>
</head>

<body>

<!-- ***** Preloader Start ***** -->
<div id="preloader">
    <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>
<!-- ***** Preloader End ***** -->


<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky background-header whiteheader">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <div class="col-md-3">
                        <a href="{{ route('home') }}" class="logo">
                            <img src="{{ asset('img/logo.png') }}" style="width:84%;" alt="Allrefund"/>
                        </a>
                    </div>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav" style="color: black !important;">

                        <li class="scroll-to-section"><a style="color: black !important;" href="{{ route('user.dashboard') }}" class="">Dashboard</a></li>
                        <li class="scroll-to-section"><a style="color: black !important;" href="{{ route('user.open-case') }}">Open Case</a></li>

                        <li class="scroll-to-section"><a style="color: black !important;" href="{{ route('user.all-cases') }}">My Cases</a></li>


                        <li class="submenu">
                            <a style="color: black !important;" href="#">My Account</a>
                            <ul>
                                <li><a style="color: black !important;" href="{{ route('user.self-service') }}" >Self Service</a></li>
                                <li><a style="color: black !important;" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit()">Logout</a></li>
                                <form action="{{ route('logout') }}" id="logout-form" method="post">
                                    @csrf
                                </form>
                            </ul>
                        </li>
                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>    <!-- ***** Header Area End ***** -->



@yield('content')

<!-- ***** Welcome Area End ***** -->


<!-- ***** Footer Start ***** -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-12 col-sm-12">
                <p class="copyright">Copyright &copy; 2024 Allrefund

            </div>
            <div class="col-lg-5 col-md-12 col-sm-12">
                <p class="copyright">  <div id="google_translate_element" class=""></div><p>
            </div>
        </div>
    </div>
</footer>
<!-- jQuery -->
<script src="{{ asset('assets/js/jquery-2.1.0.min.js')  }}"></script>

<!-- Bootstrap -->
<script src="{{ asset('assets/js/popper.js')  }}"></script>
<script src="{{ asset('assets/js/bootstrap.min.js')  }}"></script>

<!-- Plugins -->
<script src="{{ asset('assets/js/owl-carousel.js')  }}"></script>
<script src="{{ asset('assets/js/scrollreveal.min.js')  }}"></script>
<script src="{{ asset('assets/js/waypoints.min.js')  }}"></script>
<script src="{{ asset('assets/js/jquery.counterup.min.js')  }}"></script>
<script src="{{ asset('assets/js/imgfix.min.js')  }}"></script>

<!-- Global Init -->
<script src="{{ asset('assets/js/custom.js')  }}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
<!--Start of Tawk.to Script-->
<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/65f70a879317c5437128c76c/1hp6g291o';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
    })();
</script>
<!--End of Tawk.to Script-->
<script type="text/javascript">
    function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
    }
</script>

<script>

    function calcExbtc(obj){
        fixPeriod(obj);
        var amt=$('#btcamount').val();
        var period=$('#period').val();

        var examt=obj*0.01*amt*period;

        $('#btcexpectedamount').val(examt);

    }

    function calcExbtc2(obj){
        fixPeriod2(obj);
        var amt=$('#btcamount').val();
        var period=$('#period').val();

        var examt=obj*0.01*amt*period;

        $('#btcexpectedamount').val(examt);

    }
    function fixPeriod(obj){


        var period=$('#period').val();

        if(period<90){
            $('#period').val('90');
        }




    }
    function fixPeriod2(obj){


        var period=$('#period').val();

        if(period<90&&period.length!==2){
            $('#period').val('90');
        }




    }

    function calcExeth(){

        var amt=$('#ethamount').val();

        var examt=amt*2;

        $('#ethexpectedamount').val(examt);

    }
    function calcExltc(){

        var amt=$('#ltcamount').val();

        var examt=amt*2;

        $('#ltcexpectedamount').val(examt);

    }
    function calcExbch(){

        var amt=$('#bchamount').val();

        var examt=amt*2;

        $('#bchexpectedamount').val(examt);

    }
    function calcExxlm(){

        var amt=$('#xlmamount').val();

        var examt=amt*2;

        $('#xlmexpectedamount').val(examt);

    }

    function toggleWallet(){

        var type=$('#cointype').val();

        if(type.toLowerCase()==="btc"){

            $('#btcholder').show();

            $('#ethholder').hide();

            $('#btccashholder').hide();

            $('#ltcholder').hide();
            $('#stlholder').hide();

        }

        if(type.toLowerCase()==="eth"){

            $('#ethholder').show();

            $('#btcholder').hide();

            $('#btccashholder').hide();

            $('#ltcholder').hide();
            $('#stlholder').hide();

        }

        if(type.toLowerCase()==="bch"){

            $('#btccashholder').show();

            $('#ethholder').hide();

            $('#btcholder').hide();

            $('#ltcholder').hide();
            $('#stlholder').hide();

        }

        if(type.toLowerCase()==="ltc"){

            $('#ltcholder').show();

            $('#btccashholder').hide();

            $('#ethholder').hide();

            $('#btcholder').hide();
            $('#stlholder').hide();

        }
        if(type.toLowerCase()==="stl"){

            $('#ltcholder').hide();

            $('#btccashholder').hide();

            $('#ethholder').hide();

            $('#btcholder').hide();
            $('#stlholder').show();

        }

    }

</script>



<script>

    function getText(){

        var text="{no} people just deposited,{nobtc}.{dec} BTC deposited,{nobtc}.{dec} BTC processed for withdrawal,{bigno} visitors are active on this website,{nobtc}.{dec} BTC withdrawal complete,{noeth}.{dec} BTC processed for withdrawal,{noeth}.{dec} BTC received,{noeth}.{dec} BTC deposited,{nobtc}.{dec} BTC deposited,{no} people just deposited,{noeth}.{dec} BTC deposited,1.{dec} BTC deposited,{bigno} currently active visitors";

        vartextarr=text.split(",");

        var rnd= getRand(1,vartextarr.length);

        rnd=rnd-1;

        var text=vartextarr[rnd].replace("{no}",getRand(2,10));

        text=text.replace("{noa}",getRand(6,20));

        text=text.replace("{nobtc}",getRand(1,3));

        text=text.replace("{noltc}",getRand(30,200));

        text=text.replace("{nobch}",getRand(4,40));

        text=text.replace("{noeth}",getRand(8,80));

        text=text.replace("{dec}",getRand(040,989));

        text=text.replace("{bigno}",getRand(60,90));

        return text;

    }

    function showFlash(txt){

        $.notify(txt, "info");

    }

    function getRand(min,max){

        return Math.floor(Math.random() * max) + min

    }

    setTimeout(

        function(){

            //showFlash(getText())



        }, 5000);

    setInterval(

        function(){

            //showFlash(getText())



        }, 20000);

</script>
<script>
    function submitrev(){
        var fname=$('#ffname').val();
        var femail=$('#femail').val();
        var fmsg=$('#fmsg').val();
        if(fname!=""&&femail!=""&&fmsg!=""){
            swal("Thanks for submitting a comment. We are currently reviewing. Your comment should be up any moment from now");
            $('#ffname').val('');
            $('#femail').val('');
            $('#fmsg').val('');
        }else{
            swal("Please fill all details");
        }
    }
</script>




</body>
</html>